// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"context"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context) App {
	dbModel := NewDBEngine(ctx)
	biz := NewBiz(dbModel)
	api := NewApi(biz)
	app := NewApp(api)
	return app
}
